import { useMemo, useState } from 'react'
import type { Country, Dataset } from '../types'
import { distribution, formatCompact, hostedPopulation, hostedPopulationShare, linearRegression } from '../lib/analytics'
import { Chart } from '../components/Chart'
import { Coverage } from '../components/Shell'
import { CsvLink } from '../components/ExportLink'
import type { CsvRow } from '../lib/downloads'
import { chartAxisTitles } from '../lib/chartLabels'
import { indicatorDefinition } from '../lib/indicators'

const axis = { axisLine: { lineStyle: { color: '#bcccdc' } }, axisLabel: { color: '#627d98', fontSize: 11 }, splitLine: { lineStyle: { color: '#e8eef4' } } }
const tip = { backgroundColor: '#102a43', borderColor: '#102a43', textStyle: { color: '#fff', fontSize: 12 } }
const incomeOrder = ['Low income', 'Lower middle income', 'Upper middle income', 'High income']

export function ContextPressures({ data, countries, onCountry }: { data: Dataset; countries: Country[]; onCountry: (iso3: string) => void }) {
  const [displacementMode, setDisplacementMode] = useState<'absolute' | 'share'>('absolute')
  const displacementYear = data.meta.displacement_year ?? 2024
  const scored = countries.filter(c => c.ihr_composite != null)
  const incomeRows = scored.filter(c => c.income && incomeOrder.includes(c.income))
  const conflictGroups = [{ label: 'Conflict-affected', rows: scored.filter(c => c.conflict) }, { label: 'Other settings', rows: scored.filter(c => !c.conflict) }].filter(group => group.rows.length)
  const spendingRows = scored.flatMap(country => { const observation = country.context?.health_exp_pc; return observation?.value > 0 ? [{ country, spend: observation.value, year: observation.year, logSpend: Math.log10(observation.value) }] : [] })
  const fit = linearRegression(spendingRows.map(row => [row.logSpend, row.country.ihr_composite!] as [number, number]))
  const sanitationDefinition = indicatorDefinition('sanitation', data.meta.indicator_definitions)!
  const sanitationRows = scored.flatMap(country => country.context?.sanitation ? [{ country, value: country.context.sanitation.value, year: country.context.sanitation.year }] : [])
  const displacementRows = scored.flatMap(country => { const hosted = hostedPopulation(country), share = hostedPopulationShare(country); return displacementMode === 'absolute' ? hosted > 0 ? [{ country, x: hosted, hosted, share }] : [] : share != null ? [{ country, x: share, hosted, share }] : [] })

  const incomeOption = useMemo(() => ({ grid: { left: 60, right: 30, top: 22, bottom: 56 }, tooltip: { ...tip, formatter: pointTip('Income group') }, xAxis: { ...axis, type: 'category', name: chartAxisTitles.income, nameLocation: 'middle', nameGap: 36, data: incomeOrder.map(shortIncome) }, yAxis: { ...axis, min: 20, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 44 }, series: [{ type: 'scatter', data: incomeRows.map(c => ({ name: c.name, iso3: c.iso3, year: c.ihr_year, group: c.income, value: [shortIncome(c.income!), c.ihr_composite], symbolSize: populationSize(c), itemStyle: { color: c.conflict ? '#c65d4b' : '#087e8b', opacity: .82, borderColor: '#fff', borderWidth: 1 } })) }] }), [incomeRows])
  const conflictOption = useMemo(() => ({ grid: { left: 60, right: 30, top: 20, bottom: 48 }, tooltip: { ...tip }, xAxis: { ...axis, type: 'category', name: chartAxisTitles.setting, nameLocation: 'middle', nameGap: 36, data: conflictGroups.map(group => group.label) }, yAxis: { ...axis, min: 20, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 44 }, series: [{ name: 'Distribution', type: 'boxplot', data: conflictGroups.map(group => { const stats = distribution(group.rows.map(c => c.ihr_composite))!; return [stats.min, stats.q1, stats.median, stats.q3, stats.max] }), itemStyle: { color: '#d9edf0', borderColor: '#087e8b' } }, { name: 'Countries', type: 'scatter', symbolSize: 9, data: conflictGroups.flatMap((group, index) => group.rows.map(country => ({ name: country.name, iso3: country.iso3, year: country.ihr_year, group: group.label, value: [index, country.ihr_composite], itemStyle: { color: group.label === 'Conflict-affected' ? '#c65d4b' : '#2f6b9a', opacity: .78 } }))), tooltip: { formatter: pointTip('Setting') } }] }), [conflictGroups])
  const spendingOption = useMemo(() => { const xs = spendingRows.map(row => row.spend), min = Math.min(...xs), max = Math.max(...xs), line = fit ? [[min, fit.predict(Math.log10(min))], [max, fit.predict(Math.log10(max))]] : []; return { grid: { left: 70, right: 32, top: 20, bottom: 64 }, tooltip: { ...tip }, xAxis: { ...axis, type: 'log', name: chartAxisTitles.spending, nameLocation: 'middle', nameGap: 40, axisLabel: { color: '#627d98', formatter: (v: number) => `$${formatCompact(v)}` } }, yAxis: { ...axis, min: 20, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 44 }, series: [{ type: 'line', data: line, showSymbol: false, silent: true, lineStyle: { color: '#627d98', type: 'dashed', width: 1.5 } }, { type: 'scatter', symbolSize: 11, data: spendingRows.map(row => { const residual = fit ? row.country.ihr_composite! - fit.predict(row.logSpend) : null; return { name: row.country.name, iso3: row.country.iso3, value: [row.spend, row.country.ihr_composite], year: row.year, residual, itemStyle: { color: residual == null ? '#627d98' : residual >= 0 ? '#087e8b' : '#c65d4b' } } }), tooltip: { formatter: (p: any) => `<b>${p.name}</b><br/>Health spending: $${Math.round(p.value[0]).toLocaleString()} (${p.data.year})<br/>SPAR: ${p.value[1]}<br/>${p.data.residual == null ? 'Fitted relationship unavailable' : `${Math.abs(p.data.residual).toFixed(1)} points ${p.data.residual >= 0 ? 'above' : 'below'} fitted relationship`}` } }] } }, [spendingRows, fit])
  const sanitationOption = useMemo(() => ({ grid: { left: 74, right: 32, top: 18, bottom: 68 }, tooltip: { ...tip }, xAxis: { ...axis, type: 'value', min: 0, max: 100, name: `${sanitationDefinition.label} (${sanitationDefinition.unit})`, nameLocation: 'middle', nameGap: 42 }, yAxis: { ...axis, min: 20, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 44 }, series: [{ type: 'scatter', symbolSize: 11, data: sanitationRows.map(row => ({ name: row.country.name, iso3: row.country.iso3, value: [row.value, row.country.ihr_composite], year: row.year, sparYear: row.country.ihr_year, itemStyle: { color: row.country.conflict ? '#c65d4b' : '#2f6b9a', opacity: .82 } })), tooltip: { formatter: (p: any) => `<b>${p.name}</b><br/>Safely managed sanitation: ${p.value[0]}% (${p.data.year})<br/>SPAR composite: ${p.value[1]}/100 (${p.data.sparYear})` } }] }), [sanitationDefinition, sanitationRows])
  const displacementOption = useMemo(() => ({ grid: { left: 70, right: 32, top: 18, bottom: 58 }, tooltip: { ...tip }, xAxis: { ...axis, type: displacementMode === 'absolute' ? 'log' : 'value', name: displacementMode === 'absolute' ? chartAxisTitles.displacedPeople : chartAxisTitles.displacedShare, nameLocation: 'middle', nameGap: 40, axisLabel: { color: '#627d98', formatter: (v: number) => displacementMode === 'absolute' ? formatCompact(v) : `${v}%` } }, yAxis: { ...axis, min: 20, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 44 }, series: [{ type: 'scatter', data: displacementRows.map(row => ({ name: row.country.name, iso3: row.country.iso3, value: [row.x, row.country.ihr_composite], year: row.country.ihr_year, hosted: row.hosted, share: row.share, itemStyle: { color: row.country.conflict ? '#c65d4b' : '#2f6b9a', opacity: .82 }, symbolSize: 11 })), tooltip: { formatter: (p: any) => `<b>${p.name}</b><br/>Reported displaced people present: ${p.data.hosted.toLocaleString()} (UNHCR ${displacementYear})<br/>Population share: ${p.data.share == null ? 'Unavailable' : `${p.data.share.toFixed(1)}%`}<br/>SPAR composite: ${p.value[1]}/100 (${p.data.year})` } }] }), [displacementMode, displacementRows, displacementYear])
  const openCountry = (params: any) => params?.data?.iso3 && onCountry(params.data.iso3)

  return <section className="workspace context-workspace"><header className="workspace-head"><div><h1>Context &amp; pressures</h1><p>Descriptive relationships that support further country-specific assessment; they do not establish causality.</p></div></header><div className="context-grid">
    <AnalysisPanel title="Conflict-affected and other settings" subtitle={`Distribution, median and IQR · ${data.meta.fcs_note}`} count={scored.length} csvRows={scored.map(c => ({ country: c.name, setting: c.conflict ? 'Conflict-affected' : 'Other setting', spar_composite_0_100: c.ihr_composite, reference_year: c.ihr_year }))}><Chart option={conflictOption} height={360} ariaLabel="Preparedness distribution for conflict-affected and other settings" onClick={openCountry} /><CountryTable rows={scored} columns={[["Setting", c => c.conflict ? 'Conflict-affected' : 'Other setting'], ['SPAR', c => c.ihr_composite ?? '—'], ['Year', c => c.ihr_year ?? '—']]} /></AnalysisPanel>
    <AnalysisPanel title="Displacement pressure and preparedness" subtitle={`Reported displaced people present · UNHCR ${displacementYear}`} count={displacementRows.length} actions={<div className="mode-toggle" role="group" aria-label="Displacement measure"><button aria-pressed={displacementMode === 'absolute'} className={displacementMode === 'absolute' ? 'active' : ''} onClick={() => setDisplacementMode('absolute')}>People present</button><button aria-pressed={displacementMode === 'share'} className={displacementMode === 'share' ? 'active' : ''} onClick={() => setDisplacementMode('share')}>Share of population</button></div>} csvRows={displacementRows.map(row => ({ country: row.country.name, displaced_people_present: row.hosted, share_of_population_percent: row.share, unhcr_year: displacementYear, spar_composite_0_100: row.country.ihr_composite, spar_year: row.country.ihr_year }))}><Chart option={displacementOption} height={360} ariaLabel="Displacement pressure and reported preparedness" onClick={openCountry} /><CountryTable rows={displacementRows.map(row => row.country)} columns={[["Reported displaced people", c => `${hostedPopulation(c).toLocaleString()} (${displacementYear})`], ['Share of population', c => hostedPopulationShare(c) == null ? '—' : `${hostedPopulationShare(c)!.toFixed(1)}%`], ['SPAR', c => `${c.ihr_composite ?? '—'}/100`], ['SPAR year', c => c.ihr_year ?? '—']]} /></AnalysisPanel>
    <AnalysisPanel title="Safely managed sanitation and preparedness" subtitle={`${sanitationDefinition.direction} Descriptive association only.`} count={sanitationRows.length} csvRows={sanitationRows.map(row => ({ country: row.country.name, safely_managed_sanitation_percent: row.value, sanitation_year: row.year, spar_composite_0_100: row.country.ihr_composite, spar_year: row.country.ihr_year }))}><Chart option={sanitationOption} height={380} ariaLabel="Safely managed sanitation and reported preparedness" onClick={openCountry} /><CountryTable rows={sanitationRows.map(row => row.country)} columns={[["Safely managed sanitation", country => `${country.context.sanitation.value}%`], ['Sanitation year', country => country.context.sanitation.year], ['SPAR', country => `${country.ihr_composite}/100`], ['SPAR year', country => country.ihr_year]]} /></AnalysisPanel>
    <AnalysisPanel title="Preparedness relative to reported health spending" subtitle="Exploratory fitted relationship; logarithmic spending scale" count={spendingRows.length} csvRows={spendingRows.map(row => ({ country: row.country.name, current_health_expenditure_per_capita_usd: row.spend, spending_year: row.year, spar_composite_0_100: row.country.ihr_composite, spar_year: row.country.ihr_year, residual_from_fitted_relationship: fit ? row.country.ihr_composite! - fit.predict(row.logSpend) : null }))}><Chart option={spendingOption} height={380} ariaLabel="Preparedness relative to health expenditure per capita" onClick={openCountry} /><CountryTable rows={spendingRows.map(row => row.country)} columns={[["Health spending", c => `$${Math.round(c.context.health_exp_pc.value).toLocaleString()}`], ['Spending year', c => c.context.health_exp_pc.year], ['SPAR', c => c.ihr_composite], ['SPAR year', c => c.ihr_year]]} /></AnalysisPanel>
    <AnalysisPanel wide title="Income and preparedness" subtitle="Country distribution by World Bank income group; point size reflects population" count={incomeRows.length} csvRows={incomeRows.map(c => ({ country: c.name, income_group: c.income, spar_composite_0_100: c.ihr_composite, reference_year: c.ihr_year }))}><Chart option={incomeOption} height={360} ariaLabel="Preparedness scores by income group" onClick={openCountry} /><CountryTable rows={incomeRows} columns={[["Income group", c => c.income], ['SPAR', c => c.ihr_composite], ['Year', c => c.ihr_year]]} /></AnalysisPanel>
  </div></section>
}

function AnalysisPanel({ title, subtitle, count, wide = false, actions, csvRows, children }: { title: string; subtitle: string; count: number; wide?: boolean; actions?: React.ReactNode; csvRows: CsvRow[]; children: React.ReactNode }) { return <section className={`panel analysis-panel${wide ? ' wide' : ''}${actions ? ' has-actions' : ''}`}><header className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div><div className="analysis-actions">{actions}<CsvLink filename={`${slug(title)}.csv`} rows={csvRows} /><Coverage count={count} /></div></header>{children}</section> }
function CountryTable({ rows, columns }: { rows: Country[]; columns: Array<[string, (country: Country) => React.ReactNode]> }) { return <details className="data-table"><summary>View accessible data table</summary><div className="table-scroll"><table><thead><tr><th>Country</th>{columns.map(([label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(country => <tr key={country.iso3}><th>{country.name}</th>{columns.map(([label, value]) => <td key={label}>{value(country) ?? '—'}</td>)}</tr>)}</tbody></table></div></details> }
function shortIncome(income: string) { return income.replace('Lower middle', 'Lower-middle').replace('Upper middle', 'Upper-middle').replace(' income', '') }
function populationSize(country: Country) { const population = country.context?.population?.value ?? 1_000_000; return Math.max(9, Math.min(36, Math.sqrt(population / 1_000_000) * 4)) }
function pointTip(groupLabel: string) { return (p: any) => `<b>${p.name}</b><br/>${groupLabel}: ${p.data.group}<br/>SPAR: ${p.value[1]} (${p.data.year})` }
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
