import { useMemo } from 'react'
import type { Country, Dataset } from '../types'
import { Chart } from '../components/Chart'
import { capacityCoverage, hostedPopulation, hostedPopulationShare, median, peerCountries, tiedRanks, trendDelta, yearRange } from '../lib/analytics'
import { chartAxisTitles } from '../lib/chartLabels'
import { CapacityRadar } from '../components/CapacityRadar'
import type { PeerMode } from '../lib/navigation'
import { indicatorDefinition } from '../lib/indicators'
import type { CsvRow } from '../lib/downloads'
import { CsvLink } from '../components/ExportLink'
import { CountryPicker } from '../components/CountryPicker'

const axis = { axisLine: { lineStyle: { color: '#bcccdc' } }, axisLabel: { color: '#627d98', fontSize: 10 }, splitLine: { lineStyle: { color: '#e8eef4' } } }
const tip = { backgroundColor: '#102a43', borderColor: '#102a43', textStyle: { color: '#fff', fontSize: 12 } }
const contextDefinitions = [
  ['beds', 'Hospital beds', 'per 1,000 people'], ['physicians', 'Physicians', 'per 1,000 people'],
  ['nurses', 'Nurses and midwives', 'per 1,000 people'], ['health_exp_gdp', 'Current health expenditure', '% of GDP'],
  ['health_exp_pc', 'Health expenditure per capita', 'current US$ per person'], ['oop', 'Out-of-pocket expenditure', '% of current health expenditure'],
  ['imm_measles', 'Measles immunization', '% of eligible children'], ['imm_dpt', 'DPT immunization', '% of eligible children'],
  ['water', 'Safely managed drinking water', '% of population'], ['sanitation', 'Safely managed sanitation', '% of population'],
  ['life_exp', 'Life expectancy at birth', 'years'], ['u5mort', 'Under-five mortality', 'deaths per 1,000 live births'],
] as const

type Props = { data: Dataset; country: Country; setCountry: (iso: string) => void; peerMode: PeerMode; setPeerMode: (mode: PeerMode) => void }

export function CountryProfile({ data, country, setCountry, peerMode, setPeerMode }: Props) {
  const ranks = useMemo(() => tiedRanks(data.countries), [data.countries])
  const topPerformer = useMemo(() => data.countries.filter(item => item.ihr_composite != null).sort((a, b) => b.ihr_composite! - a.ihr_composite!)[0], [data.countries])
  const capacityRows = useMemo(() => data.meta.capacity_order.map(name => {
    const value = country.capacities?.[name] ?? null
    const regional = median(data.countries.map(item => item.capacities?.[name]))
    return { name, value, regional, top: topPerformer.capacities?.[name] ?? null, gap: value != null && regional != null ? value - regional : null, year: country.capacity_years?.[name] ?? null, regionalYears: yearRange(data.countries.map(item => item.capacity_years?.[name])), coverage: data.countries.filter(item => Number.isFinite(item.capacities?.[name])).length }
  }), [country, data, topPerformer])
  const availableCapacities = capacityRows.filter(row => row.value != null && row.regional != null && row.top != null)
  const gapRows = [...availableCapacities].sort((a, b) => a.gap! - b.gap!)
  const contextRows = useMemo(() => contextDefinitions.flatMap(([key, label, unit]) => {
    const observation = country.context?.[key]
    const regional = data.meta.context_median?.[key] ?? median(data.countries.map(item => item.context?.[key]?.value))
    if (!observation || regional == null) return []
    const reporting = data.countries.filter(item => Number.isFinite(item.context?.[key]?.value))
    return [{ key, label, unit, value: observation.value, year: observation.year, regional, coverage: reporting.length, regionalYears: yearRange(reporting.map(item => item.context[key].year)), scale: indicatorDefinition(key, data.meta.indicator_definitions)?.scale ?? 'nonnegative', direction: indicatorDefinition(key, data.meta.indicator_definitions)?.direction ?? 'Interpret in context.' }]
  }), [country, data])
  const peerGroup = useMemo(() => peerCountries(data.countries, country, peerMode), [country, data.countries, peerMode])
  const peers = [...peerGroup.countries].sort((a, b) => (a.ihr_composite ?? Infinity) - (b.ihr_composite ?? Infinity))
  const peerRanks = tiedRanks(peerGroup.countries)
  const delta = trendDelta(country)
  const displaced = hostedPopulation(country)
  const displacedShare = hostedPopulationShare(country)

  const gapOption = { grid: { left: 190, right: 42, top: 16, bottom: 56 }, tooltip: { ...tip }, xAxis: { ...axis, type: 'value', name: chartAxisTitles.capacityGap, nameLocation: 'middle', nameGap: 34 }, yAxis: { ...axis, type: 'category', name: chartAxisTitles.capacityDomain, nameLocation: 'middle', nameGap: 176, data: gapRows.map(row => row.name), axisLabel: { color: '#334e68', fontSize: 10 } }, series: [{ type: 'bar', barWidth: 12, data: gapRows.map(row => ({ value: Number(row.gap?.toFixed(1)), itemStyle: { color: row.gap! < 0 ? '#c65d4b' : '#2f6b9a', borderType: row.gap! < 0 ? 'dashed' : 'solid' }, label: row.gap === 0 ? { show: true, position: 'right', color: '#334e68', formatter: '0' } : { show: true, position: 'inside', color: '#fff', formatter: `${row.gap! > 0 ? '+' : ''}${row.gap?.toFixed(0)}` } })), tooltip: { formatter: (point: any) => { const row = gapRows[point.dataIndex]; return `<b>${row.name}</b><br/>Difference: ${row.gap! > 0 ? '+' : ''}${row.gap?.toFixed(1)} SPAR points<br/>Country: ${row.value}/100 (${row.year ?? 'year unavailable'})<br/>Regional median: ${row.regional?.toFixed(1)}/100 (${row.regionalYears})` } } }] }
  const trendOption = { grid: { left: 64, right: 28, top: 24, bottom: 60 }, tooltip: { ...tip, trigger: 'axis' }, xAxis: { ...axis, type: 'category', name: chartAxisTitles.referenceYear, nameLocation: 'middle', nameGap: 36, data: country.ihr_trend.map(point => point.year) }, yAxis: { ...axis, min: 0, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 46 }, series: [{ type: 'line', smooth: true, symbolSize: 7, data: country.ihr_trend.map(point => point.value), lineStyle: { color: '#087e8b', width: 3 }, itemStyle: { color: '#087e8b' }, areaStyle: { color: 'rgba(8,126,139,.10)' } }] }
  const peerOption = { grid: { left: 130, right: 46, top: 18, bottom: 56 }, tooltip: { ...tip }, xAxis: { ...axis, min: 0, max: 100, name: chartAxisTitles.spar, nameLocation: 'middle', nameGap: 34 }, yAxis: { ...axis, type: 'category', name: chartAxisTitles.country, nameLocation: 'middle', nameGap: 116, data: peers.map(peer => peer.name), axisLabel: { color: '#334e68', fontSize: 10 } }, series: [{ type: 'bar', barWidth: 11, data: peers.map(peer => ({ value: peer.ihr_composite, iso3: peer.iso3, year: peer.ihr_year, rank: peerRanks.get(peer.iso3), itemStyle: { color: peer.iso3 === country.iso3 ? '#c65d4b' : '#2f6b9a' } })), label: { show: true, position: 'right', color: '#334e68' }, tooltip: { formatter: (point: any) => `<b>${point.name}</b><br/>SPAR composite: ${point.value}/100 (${point.data.year ?? 'year unavailable'})<br/>Peer rank: ${point.data.rank}/${peers.length}; ties share rank` } }] }

  return <section className="workspace country-profile">
    <header className="workspace-head"><div><h1>Country profile</h1><p>Reported preparedness capacities, health-system context, peer position, and data limitations.</p></div><label>Country<CountryPicker countries={data.countries} value={country.iso3} onChange={setCountry} /></label></header>
    <section className="country-identity"><div><h2>{country.name}</h2><p>{country.income ?? 'Income classification unavailable'} · {country.conflict ? 'Conflict-affected setting' : 'Other setting'} ({data.meta.fcs_note})</p></div><div><b>{displaced.toLocaleString()}</b><span>reported displaced people present{data.meta.displacement_year ? ` · ${data.meta.displacement_year}` : ''}</span><small>{displacedShare == null ? 'Population share unavailable' : `${displacedShare.toFixed(1)}% of national population`}</small></div></section>
    <div className="country-summary"><Summary label="Latest SPAR composite" value={country.ihr_composite == null ? '—' : `${country.ihr_composite}`} suffix="/100" detail={country.ihr_year ? `Reported ${country.ihr_year}` : 'Year unavailable'} /><Summary label="Regional rank" value={ranks.get(country.iso3) ?? '—'} suffix={` / ${data.countries.filter(item => item.ihr_composite != null).length}`} detail="Ties share the same rank" /><Summary label="Trajectory" value={delta == null ? '—' : `${delta > 0 ? '+' : ''}${delta.toFixed(0)}`} detail={delta == null ? 'Insufficient observations' : `${country.ihr_trend[0].year}–${country.ihr_trend.at(-1)!.year} · SPAR points`} /><Summary label="Capacity coverage" value={capacityCoverage(country, data.meta.capacity_order)} suffix={` / ${data.meta.capacity_order.length}`} detail="Available SPAR domains" /></div>
    <div className="profile-grid">
      <ProfilePanel title="Capacity profile versus region" subtitle={`Interactive reported-capacity profile: ${country.name}, regional median, and ${topPerformer.name} as the highest composite`} csvRows={capacityExport(availableCapacities, country.name, topPerformer.name)}>{availableCapacities.length ? <><CapacityRadar rows={availableCapacities as any} country={country.name} topName={topPerformer.name} total={data.countries.length} /><CapacityTable rows={availableCapacities} total={data.countries.length} topName={topPerformer.name} /></> : <Unavailable country={country.name} />}</ProfilePanel>
      <ProfilePanel title="Capacity gaps" subtitle="Descriptive difference from the regional median; not a performance or investment measure" csvRows={capacityExport(gapRows, country.name, topPerformer.name)}>{gapRows.length ? <><Chart option={gapOption} height={560} ariaLabel={`Capacity differences between ${country.name} and regional medians`} /><CapacityTable rows={gapRows} total={data.countries.length} includeGap topName={topPerformer.name} /></> : <Unavailable country={country.name} />}</ProfilePanel>
      <ProfilePanel title="SPAR trend over time" subtitle="Reported annual SPAR composite score; the y-axis uses the full 0–100 scale" csvRows={country.ihr_trend.map(point => ({ country: country.name, reference_year: point.year, spar_composite_0_100: point.value }))}><Chart option={trendOption} height={430} ariaLabel={`SPAR composite trend for ${country.name}`} /><TrendTable country={country} /></ProfilePanel>
      <ProfilePanel title="Peer comparison" subtitle={`SPAR composite among ${peerGroup.label}; selected country highlighted${peerGroup.fallback ? ' · fallback applied because fewer than three selected peers report' : ''}`} actions={<div className="mode-toggle" role="group" aria-label="Peer group">{(['income', 'conflict', 'all'] as PeerMode[]).map(mode => <button key={mode} aria-pressed={peerMode === mode} className={peerMode === mode ? 'active' : ''} onClick={() => setPeerMode(mode)}>{mode === 'income' ? 'Income peers' : mode === 'conflict' ? 'Conflict-status peers' : 'All MENA'}</button>)}</div>} csvRows={peers.map(peer => ({ peer_definition: peerGroup.label, rank: peerRanks.get(peer.iso3), country: peer.name, spar_composite_0_100: peer.ihr_composite, reference_year: peer.ihr_year }))}><Chart option={peerOption} height={Math.max(430, peers.length * 34 + 100)} ariaLabel={`Preparedness comparison for ${country.name} and ${peerGroup.label}`} onClick={(point: any) => point?.data?.iso3 && setCountry(point.data.iso3)} /><PeerTable rows={peers} ranks={peerRanks} onCountry={setCountry} /></ProfilePanel>
      <ProfilePanel title="Health-system context versus regional median" subtitle="Actual values and units; each indicator row uses its own scale and reference years" wide csvRows={contextRows.map(row => ({ country: country.name, indicator: row.label, country_value: row.value, unit: row.unit, country_year: row.year, regional_median: row.regional, regional_years: row.regionalYears, coverage: `${row.coverage}/${data.countries.length}` }))}><ContextComparison rows={contextRows} country={country.name} /><ContextTable rows={contextRows} total={data.countries.length} /></ProfilePanel>
    </div>
  </section>
}

function ContextComparison({ rows, country }: { rows: ContextRow[]; country: string }) { return <div className="context-comparison" aria-label={`Health-system context for ${country} compared with regional medians`}>{rows.map(row => { const scale = row.scale === 'percentage' ? 100 : niceMaximum(Math.max(row.value, row.regional)); return <div className="context-row" key={row.key}><div><b>{row.label}</b><span>{row.unit} · scale 0–{formatValue(scale)}</span></div><div className="bullet-meta"><b>{country}: {formatValue(row.value)}</b><span>{row.year}</span><small>{row.direction}</small></div><div className="bullet-track"><i style={{ width: `${Math.min(100, row.value / scale * 100)}%` }} /><em style={{ left: `${Math.min(100, row.regional / scale * 100)}%` }} aria-label={`Regional median ${formatValue(row.regional)} ${row.unit}`} /></div><div className="bullet-median">Regional median: <b>{formatValue(row.regional)}</b> · {row.regionalYears} · coverage {row.coverage}</div></div>})}</div> }
function Summary({ label, value, suffix, detail }: { label: string; value: string | number; suffix?: string; detail: string }) { return <div><span>{label}</span><strong>{value}<small>{suffix}</small></strong><p>{detail}</p></div> }
function ProfilePanel({ title, subtitle, wide = false, actions, csvRows, children }: { title: string; subtitle: string; wide?: boolean; actions?: React.ReactNode; csvRows: CsvRow[]; children: React.ReactNode }) { return <section className={`panel profile-panel${wide ? ' wide' : ''}`}><header className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div><div className="analysis-actions">{actions}<CsvLink filename={`${slug(title)}.csv`} rows={csvRows} /></div></header>{children}</section> }
function Unavailable({ country }: { country: string }) { return <div className="profile-unavailable"><b>Detailed capacity profile unavailable</b><p>No detailed SPAR capacity observations are available for {country}. Missing values are not shown as zero.</p></div> }
type CapacityRow = { name: string; value: number | null; regional: number | null; top: number | null; gap: number | null; year: number | null; regionalYears: string; coverage: number }
type ContextRow = { key: string; label: string; unit: string; value: number; year: number; regional: number; coverage: number; regionalYears: string; scale: string; direction: string }
function CapacityTable({ rows, total, topName, includeGap = false }: { rows: CapacityRow[]; total: number; topName: string; includeGap?: boolean }) { return <details className="data-table"><summary>View accessible data table</summary><div className="table-scroll"><table><thead><tr><th>Capacity domain</th><th>Country</th><th>Year</th><th>Regional median</th><th>Median years</th><th>{topName}</th>{includeGap ? <th>Difference</th> : null}<th>Coverage</th></tr></thead><tbody>{rows.map(row => <tr key={row.name}><th>{row.name}</th><td>{row.value}/100</td><td>{row.year ?? '—'}</td><td>{row.regional?.toFixed(1)}/100</td><td>{row.regionalYears}</td><td>{row.top}/100</td>{includeGap ? <td>{row.gap! > 0 ? '+' : ''}{row.gap?.toFixed(1)} points</td> : null}<td>{row.coverage}/{total}</td></tr>)}</tbody></table></div></details> }
function ContextTable({ rows, total }: { rows: ContextRow[]; total: number }) { return <details className="data-table"><summary>View accessible data table</summary><div className="table-scroll"><table><thead><tr><th>Indicator</th><th>Country value</th><th>Year</th><th>Regional median</th><th>Median years</th><th>Coverage</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><th>{row.label}</th><td>{formatValue(row.value)} {row.unit}</td><td>{row.year}</td><td>{formatValue(row.regional)} {row.unit}</td><td>{row.regionalYears}</td><td>{row.coverage}/{total}</td></tr>)}</tbody></table></div></details> }
function TrendTable({ country }: { country: Country }) { return <details className="data-table"><summary>View accessible data table</summary><div className="table-scroll"><table><thead><tr><th>Reference year</th><th>SPAR composite</th></tr></thead><tbody>{country.ihr_trend.map(point => <tr key={point.year}><th>{point.year}</th><td>{point.value}/100</td></tr>)}</tbody></table></div></details> }
function PeerTable({ rows, ranks, onCountry }: { rows: Country[]; ranks: Map<string, number>; onCountry: (iso: string) => void }) { return <details className="data-table"><summary>View accessible data table</summary><div className="table-scroll"><table><thead><tr><th>Peer rank</th><th>Country</th><th>SPAR composite</th><th>Year</th></tr></thead><tbody>{rows.map(row => <tr key={row.iso3} tabIndex={0} role="link" onClick={() => onCountry(row.iso3)} onKeyDown={event => (event.key === 'Enter' || event.key === ' ') && onCountry(row.iso3)}><td>{ranks.get(row.iso3)}</td><th>{row.name}</th><td>{row.ihr_composite}/100</td><td>{row.ihr_year ?? '—'}</td></tr>)}</tbody></table></div></details> }
function formatValue(value: number) { return new Intl.NumberFormat('en', { maximumFractionDigits: 1 }).format(value) }
function niceMaximum(value: number) { const magnitude = 10 ** Math.floor(Math.log10(Math.max(1, value))); return Math.ceil(value * 1.15 / magnitude) * magnitude }
function slug(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
function capacityExport(rows: CapacityRow[], country: string, top: string): CsvRow[] { return rows.map(row => ({ capacity: row.name, country, country_score_0_100: row.value, country_year: row.year, regional_median_0_100: row.regional, regional_years: row.regionalYears, highest_composite_country: top, top_country_capacity_score_0_100: row.top, difference_from_median_points: row.gap, coverage: row.coverage })) }
