import type { Dataset } from '../types'
import { contextIndicators } from '../lib/indicators'

export function Methodology({ data }: { data: Dataset }) {
  const refresh = Object.entries(data.meta.source_refresh ?? {})
  const definitions = data.meta.indicator_definitions?.length ? data.meta.indicator_definitions : contextIndicators
  const quality = data.countries.map(country => ({ country: country.name, iso3: country.iso3, spar: country.ihr_composite == null ? 'Missing' : `${country.ihr_year}`, capacities: `${data.meta.capacity_order.filter(capacity => Number.isFinite(country.capacities?.[capacity])).length}/${data.meta.capacity_order.length}`, world_bank: `${Object.keys(country.context ?? {}).length} indicators`, displacement: data.meta.displacement_year ?? 'Unavailable' }))
  return <section className="workspace methodology">
    <header className="workspace-head"><div><h1>Methodology &amp; data quality</h1><p>Scope, definitions, calculations, provenance, action governance, comparability, and refresh status.</p></div></header>
    <div className="method-grid">
      <section className="panel"><h2>Purpose and boundaries</h2><p>This strategic intelligence product supports health ministers, government officials, WHO/UN stakeholders, donors, and programme teams in reviewing reported preparedness capacity. It is not a real-time outbreak-surveillance, early-warning, audit, or causal-inference system.</p><p><b>Geographic scope:</b> {data.countries.map(country => country.name).sort().join(', ')}.</p><p>The 21-country scope is a product definition for regional analysis and does not express a position on legal status, borders, or political recognition.</p></section>
      <section className="panel"><h2>Current release</h2><dl><dt>Generated</dt><dd>{data.meta.generated}</dd><dt>Last valid refresh</dt><dd>{data.meta.last_successful_refresh ?? 'Unavailable'}</dd><dt>Schema version</dt><dd>{data.meta.schema_version ?? 'Legacy snapshot'}</dd><dt>Country denominator</dt><dd>{data.countries.length}</dd><dt>Capacity domains</dt><dd>{data.meta.capacity_order.length}</dd><dt>Displacement year</dt><dd>{data.meta.displacement_year ?? 'Unavailable'}</dd><dt>Conflict classification</dt><dd>{data.meta.fcs_note}</dd></dl><p>A refresh is published only after source and schema checks pass. On failure, the previous valid static snapshot remains available and the workflow reports the affected source.</p></section>
      <section className="panel wide-method"><h2>Calculation methods</h2><ul><li><b>Valid observations:</b> null, missing, and non-finite values are excluded; they are never converted to zero.</li><li><b>Median:</b> middle ordered value, or mean of the two middle values for even samples.</li><li><b>Quartiles:</b> linear interpolation at positions (n−1)×0.25 and (n−1)×0.75.</li><li><b>Ranks:</b> descending competition ranks; equal scores share rank and the next rank is skipped.</li><li><b>Trends:</b> latest reported score minus earliest reported score; reference period is shown.</li><li><b>Peers:</b> income or conflict-status peers reporting SPAR; fewer than three falls back to all reporting countries.</li><li><b>Spending relationship:</b> ordinary least squares of SPAR on log10 current health expenditure per capita. “Above/below fitted relationship” is a residual description, not efficiency.</li><li><b>Displacement share:</b> UNHCR-reported refugees, asylum-seekers, and internally displaced people present divided by World Bank national population, ×100.</li></ul></section>
      <section className="panel source-list"><h2>Source registry</h2>{refresh.map(([key, source]) => <div key={key}><b>{sourceName(key)} · {source.status}</b><span>Reference year(s): {source.reference_year ?? 'Unavailable'} · country coverage: {source.coverage}/{data.countries.length}</span><span>Retrieved {source.retrieved_at}</span><a className="source-endpoint" href={source.endpoint.startsWith('http') ? source.endpoint : undefined}>{source.endpoint}</a></div>)}</section>
      <section className="panel"><h2>Limitations</h2><ul><li>SPAR is a State Party self-assessment and is not an independent performance audit.</li><li>Cross-country associations are ecological and descriptive; they do not establish causality.</li><li>Indicators use mixed reference years, which are displayed with each value.</li><li>UNHCR categories describe reported populations and may differ in coverage and definition by setting.</li><li>{data.meta.fcs_note} is static and versioned; the application does not infer conflict status.</li><li>Small peer groups and missing country observations can materially affect comparisons.</li><li>Occupied Palestinian territory has a 2025 SPAR composite but no published detailed domain observations in the queried WHO capacity endpoints; missing capacities remain missing.</li></ul></section>
      <section className="panel wide-method"><h2>Indicator dictionary</h2><div className="table-scroll"><table><thead><tr><th>Indicator</th><th>Definition</th><th>Unit</th><th>Source code</th><th>Source</th><th>Scale</th><th>Interpretation</th></tr></thead><tbody>{definitions.map(item => <tr key={item.key}><th>{item.label}</th><td>{item.definition}</td><td>{item.unit}</td><td>{item.source_code}</td><td>{item.source}</td><td>{item.scale}</td><td>{item.direction}</td></tr>)}</tbody></table></div></section>
      <section className="panel wide-method"><h2>Country-by-source data quality</h2><div className="table-scroll"><table><thead><tr><th>Country</th><th>SPAR composite year</th><th>Capacity coverage</th><th>World Bank context</th><th>UNHCR year</th></tr></thead><tbody>{quality.map(row => <tr key={row.iso3}><th>{row.country}</th><td>{row.spar}</td><td>{row.capacities}</td><td>{row.world_bank}</td><td>{row.displacement}</td></tr>)}</tbody></table></div></section>
    </div>
  </section>
}

function sourceName(key: string) { return ({ who_composite: 'WHO SPAR composite', who_capacities: 'WHO SPAR capacities', world_bank: 'World Bank indicators', unhcr: 'UNHCR displacement', conflict_classification: 'Conflict classification' } as Record<string, string>)[key] ?? key }
